### ISSUE TITLE
When any other lightbox is selected, besides FancyBox we should display a message

### ISSUE THREAD

**Issue by cristianraiber** [WPChill/modula-lightboxes#1]
The logic here is that Fancybox has A LOT of options and all the other lightboxes have NONE. While we're trying to kill off all the other lightbox scripts and continue with just FancyBox, I think it makes sense to slightly nudge users into ditching any other lightbox for a more feature rich one.

**Comment by giucu91** [comment]
@andyluak fa o lista pe 3 coloane cu toate setarile din fancybox.

La sfarsit sa scrii :
Since Modula v2.3.0 Fancybox is the only officially supported lightbox. cu bold

**Comment by razvanaldea89** [comment]
Added commit https://github.com/MachoThemes/modula-lightboxes/commit/f521380fad618d5e2683dd04339f39604b436525
